### PR TITLE
Chapter 4 revisions

### PR DESCRIPTION
**Pull request by TeddyBear06**

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Thanks a bunch @TeddyBear06 I just pushed chapter 6 transcripts to the repo too.

**Comment by TeddyBear06** [comment]
Great 😊

**Comment by mikeckennedy** [comment]
Just pushed the final 4 chapters. It's all there for you when you're ready.

**Comment by TeddyBear06** [comment]
Perfect 😉

**Pull request merged**
